# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('lamina', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32)),
                ('textura', models.CharField(max_length=32)),
                ('aumento', models.IntegerField()),
                ('cor', models.CharField(max_length=32)),
                ('tamanho', models.CharField(max_length=32)),
                ('posicao_x', models.FloatField()),
                ('posicao_y', models.FloatField()),
                ('relevo', models.CharField(max_length=128)),
                ('formato_cristal', models.CharField(max_length=128)),
                ('clivagem', models.BooleanField()),
                ('fratura', models.BooleanField()),
                ('minerios_contato', models.CharField(max_length=128)),
                ('extincao', models.CharField(max_length=64)),
                ('comentario', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='minerios')),
                ('angulo', models.FloatField()),
                ('luz', models.BooleanField()),
                ('chapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_schema.Chapa')),
            ],
        ),
        migrations.CreateModel(
            name='Minerio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minerio', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='chapa',
            name='minerio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_schema.Minerio'),
        ),
    ]
